package DAO;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import model.Customers;
import model.Users;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class CustomerDaoImpl {
    public static ObservableList<Customers> getAllCustomers() throws SQLException {
        ObservableList<Customers> allCustomers = FXCollections.observableArrayList();
        ResultSet result = Query.getRS("select * from customers");
        while(result.next()){
            int custID = result.getInt("Customer_ID");
            String custName = result.getString("Customer_Name");
            String custAddress = result.getString("Address");
            String custPostal = result.getString("Postal_Code");
            String custPhone = result.getString("Phone");
            int custDivID = result.getInt("Division_ID");
            Customers custResult = new Customers(custID, custName, custAddress, custPostal, custPhone, custDivID);
            allCustomers.add(custResult);
        }
        return allCustomers;
    }

    public static void addCustomer(String custName, String custAddress, String custPostal, String custPhone, int custDivID) throws SQLException { //HOW AUTOGENERATED ID
        String sql = "INSERT INTO customers VALUES (?,?,?,?,?,NULL, NULL, NULL, NULL,?)";
        PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

        ResultSet rs = ps.getGeneratedKeys();
        rs.next();
        int custID = rs.getInt(1);

        ps.setInt(0, custID);
        ps.setString (1, custName);
        ps.setString(2, custAddress);
        ps.setString(3, custPostal);
        ps.setString(4, custPhone);
        ps.setInt(9, custDivID);

        ps.execute();
    }

}
